eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registery: true 
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:8761/eureka/

microservice:
  product-service:
    endpoints:
      endpoint:
           uri:http://PRODUCT-SERVICE/api/v1/product

  microservice:
  loyalty-service:
    endpoints:
      endpoint:
           uri:http://LOYALTY-SERVICE/api/v1/loyalty/coupon

  microservice:
  basket-service:
    endpoints:
      endpoint:
           uri:http://BASKET-SERVICE/api/v1/basket
